=== T-Ritthikrai/IDRT-Import-and-Mapping-Tool/de.umg.mi.idrt.ioe/i2b2plugin.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/i2b2plugin" xmlns:tns="http://www.example.org/i2b2plugin" elementFormDefault="qualified">



    <complexType name="observation">
    	<sequence>
    		<element name="patient_id" type="string"></element>
    		<element name="event_id" type="string"></element>
            <element name="instance_num" type="string"></element>
            <element name="value" type="string"></element>
    		<element name="start_date" type="string"></element>
    		<element name="end_date" type="string"></element>
    	</sequence>
    </complexType>

    <complexType name="column">
    	<sequence>
            <element name="header" type="string"></element>
            <element name="modifier" type="boolean"></element>
            <element name="observation" type="tns:observation"></element>
    	</sequence>
    </complexType>



    <complexType name="tab">
    	<sequence>
            <element name="tabName" type="string"></element>
            <element name="column" type="tns:column"></element>
    	</sequence>
    </complexType>

    <element name="tab" type="tns:tab"></element>
</schema>

=== T-Ritthikrai/IDRT-Import-and-Mapping-Tool/de.umg.mi.idrt.ioe/i2b2plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:tab xmlns:tns="http://www.example.org/i2b2plugin" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/i2b2plugin i2b2plugin.xsd ">
  <tns:tabName>tns:tabName</tns:tabName>
  <tns:column>
    <tns:header>tns:header</tns:header>
    <tns:modifier>true</tns:modifier>
    <tns:observation>
      <tns:patient_id>tns:patient_id</tns:patient_id>
      <tns:event_id>tns:event_id</tns:event_id>
      <tns:instance_num>tns:instance_num</tns:instance_num>
      <tns:value>tns:value</tns:value>
      <tns:start_date>tns:start_date</tns:start_date>
      <tns:end_date>tns:end_date</tns:end_date>
    </tns:observation>
  </tns:column>
</tns:tab>
